apiVersion : apps/v1
kind: Deployment
metadata:
  name: "cicdakstemp5122201-fd26"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "cicdakstemp5122201-fd26"
  template:
    metadata:
      labels:
        app: "cicdakstemp5122201-fd26"
    spec:
      containers:
        - name: "cicdakstemp5122201-fd26"
          image: "crazk8sehiebdpdv2i7fmty6.azurecr.io/cicdakstemp5122201"
          ports:
          - containerPort: 2000