apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksaksdevx00-ee99"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksaksdevx00-ee99"
  template:
    metadata:
      labels:
        app: "aksaksdevx00-ee99"
    spec:
      containers:
        - name: "aksaksdevx00-ee99"
          image: "aksdevx01registry.azurecr.io/aksaksdevx00"
          ports:
          - containerPort: 2000