apiVersion: v1
kind: Service
metadata:
  name: flask-svc-32423-test2
  namespace: flask-svc-32423-test2
spec:
  type: LoadBalancer
  selector:
    app: flask-svc-32423-test2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80