apiVersion: v1
kind: Service
metadata:
    name: "cicdakstemp5122201-fd26"
    labels:
        app: "cicdakstemp5122201-fd26"
spec:
    type: LoadBalancer
    ports:
    - port: 2000
      targetPort: 2000
      protocol: TCP
      name: http
    selector:
        app: "cicdakstemp5122201-fd26"