apiVersion: v1
kind: Service
metadata:
  name: flsk-svc-41223-run0
  namespace: flsk-svc-41223-run0-ns
spec:
  type: LoadBalancer
  selector:
    app: flsk-svc-41223-run0
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80