apiVersion: v1
kind: Service
metadata:
    name: "aksaksdevx00-ee99"
    labels:
        app: "aksaksdevx00-ee99"
spec:
    type: LoadBalancer
    ports:
    - port: 2000
      targetPort: 2000
      protocol: TCP
      name: http
    selector:
        app: "aksaksdevx00-ee99"