on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: crazk8sehiebdpdv2i7fmty6.azurecr.io
        username: ${{ secrets.acr_crazk8sehiebdpdv2i7fmty6_username }}
        password: ${{ secrets.acr_crazk8sehiebdpdv2i7fmty6_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t crazk8sehiebdpdv2i7fmty6.azurecr.io/cicdakstemp5122201:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push crazk8sehiebdpdv2i7fmty6.azurecr.io/cicdakstemp5122201:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_cicdakstemp5122201_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep flaskapp-12-21-22 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace flaskapp-12-21-22`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: flaskapp-12-21-22
        container-registry-url: crazk8sehiebdpdv2i7fmty6.azurecr.io
        container-registry-username: ${{ secrets.acr_crazk8sehiebdpdv2i7fmty6_username }}
        container-registry-password: ${{ secrets.acr_crazk8sehiebdpdv2i7fmty6_password }}
        secret-name: cicdakstemp5dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: flaskapp-12-21-22
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          crazk8sehiebdpdv2i7fmty6.azurecr.io/cicdakstemp5122201:${{ github.sha }}
        imagepullsecrets: |
          cicdakstemp5dockerauth
