on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aksdevx01registry.azurecr.io
        username: ${{ secrets.acr_aksdevx01registry_username }}
        password: ${{ secrets.acr_aksdevx01registry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t aksdevx01registry.azurecr.io/aksdevx01:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push aksdevx01registry.azurecr.io/aksdevx01:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksdevx01_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep flask-app-svc-ns-01 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace flask-app-svc-ns-01`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: flask-app-svc-ns-01
        container-registry-url: aksdevx01registry.azurecr.io
        container-registry-username: ${{ secrets.acr_aksdevx01registry_username }}
        container-registry-password: ${{ secrets.acr_aksdevx01registry_password }}
        secret-name: aksdevx01dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: flask-app-svc-ns-01
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          aksdevx01registry.azurecr.io/aksdevx01:${{ github.sha }}
        imagepullsecrets: |
          aksdevx01dockerauth
